Exit if can't crate ~/.config/pushbullet

diff --git a/pushblast b/pushblast
--- a/pushblast
+++ b/pushblast
@@ -46,7 +46,12 @@ if [[ $API_KEY_OLD != "" ]] ; then
   API_KEY=$API_KEY_OLD
 fi
 
-touch ~/.config/pushbullet
+touch ~/.config/pushbullet > /dev/null 2>&1
+if [[ $? -gt 0 ]] ; then
+  echo "Can't create ~/.config/pushbullet"
+  exit 1
+fi
+
 echo "API_KEY=$API_KEY" > ~/.config/pushbullet
 
 if [[ $DEV_NAME = "" && $DEV_NAME_OLD = "" ]] ; then
